apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/trilogy-group/ws-eng-event-ticketing-assessment-infra.git'
    targetRevision: HEAD
    path: infra
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai-task-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
